### ISSUE TITLE
Cannot import opentype

### ISSUE THREAD

**Issue by fastplayer95** [googledrive/PyDrive#119]
After trying to deploy a script on a debian machine i ran into a missing import
Since i couldn't find any other occurances of missing the opentype import im posting this here 

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from pydrive.auth import GoogleAuth
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 9, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
```

EDIT:
I may should add:

Python version ist: 2.7.9
importing pydrive works fine
importing GoogleAuth does not, neither does `from pydrive.drive import GoogleDrive`

```
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrive
>>> 
>>> 
>>> 
>>> from pydrive.auth import GoogleAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 9, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype

```

**Comment by fastplayer95** [comment]
I finally found the solution myself after looking into the `pyasn1_modules` Github repo.
`rfc2459.py ` does not import opentype....
 
reinstalling `pyasn1_modules` manually did it for me
`pip install pyasn1_modules`

**Comment by anna-pol** [comment]
maybe someone can help me with this error
ImportError                               Traceback (most recent call last)
<ipython-input-1-2053812d0613> in <module>()
----> 1 import google2pandas

C:\Users\Anna\Anaconda2\lib\site-packages\google2pandas\__init__.py in <module>()
      6 
      7 # bring classes directly into package namespace
----> 8 from ._panalysis_ga import GoogleAnalyticsQuery, GoogleAnalyticsQueryV4, GoogleMCFQuery
      9 

C:\Users\Anna\Anaconda2\lib\site-packages\google2pandas\_panalysis_ga.py in <module>()
      2 
      3 from googleapiclient.discovery import build
----> 4 from oauth2client import client, file, tools
      5 from oauth2client.service_account import ServiceAccountCredentials
      6 from sys import stdout

ImportError: No module named oauth2client
