### ISSUE TITLE
Two tests fail with python2.7

### ISSUE THREAD

**Issue by mitya57** [googledrive/PyDrive#35]
When running the testsuite, I get:
```
======================================================================
FAIL: test_01_LocalWebserverAuthWithClientConfigFromFile (pydrive.test.test_oauth.GoogleAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmitry/upstream/PyDrive/pydrive/test/test_oauth.py", line 19, in test_01_LocalWebserverAuthWithClientConfigFromFile
    self.CheckCredentialsFile('credentials/1.dat')
  File "/home/dmitry/upstream/PyDrive/pydrive/test/test_oauth.py", line 71, in CheckCredentialsFile
    self.assertEqual(ga.access_token_expired, no_file)
AssertionError: True != False

======================================================================
FAIL: test_02_LocalWebserverAuthWithClientConfigFromSettings (pydrive.test.test_oauth.GoogleAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmitry/upstream/PyDrive/pydrive/test/test_oauth.py", line 30, in test_02_LocalWebserverAuthWithClientConfigFromSettings
    self.CheckCredentialsFile('credentials/2.dat')
  File "/home/dmitry/upstream/PyDrive/pydrive/test/test_oauth.py", line 71, in CheckCredentialsFile
    self.assertEqual(ga.access_token_expired, no_file)
AssertionError: True != False
```
Other tests pass successfully.
When running the testsuite I have some auth prompts which I handle quickly, so this should not be a problem.

**Comment by RNabel** [comment]
Test suite has been updated, and all tests should be passing now. If you encounter any further issues please list them here!
