### ISSUE TITLE
QuickStart instructions incompatible with Python 3

### ISSUE THREAD

**Issue by mfeif** [googledrive/PyDrive#58]
Running the quickstart.py code:

```python
from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication
```

results in a syntax error.

I guess I didn't see anywhere that PyDrive wasn't Py3K compatible :-(

**Comment by wernight** [comment]
````
Traceback (most recent call last):
  File "...", line 5, in <module>
    from pydrive.auth import GoogleAuth
  File "/usr/local/lib/python3.4/dist-packages/pydrive/auth.py", line 160
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
````

**Comment by RNabel** [comment]
The version on master is now Python 3 compatible.
