### ISSUE TITLE
Got an error: Httplib.ResponseNotReady

### ISSUE THREAD

**Issue by xyzrico** [googledrive/PyDrive#69]
Hello. I'm starting with PyDrive. So I stared by running the quickstart.py in the documentation.
```python
from pydrive.drive import GoogleDrive
from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.CommandLineAuth()
drive = GoogleDrive(gauth)

file1 = drive.CreateFile({'title': 'Hello.txt'})
file1.SetContentString('Hello World!')
file1.Upload()
```
So when I execute the code. It lunch my browser, and when I select my account and accept.
it redirect to my http://localhost:8080/. But the my code fail. raising an Httplib.ResponseNotReady
in my console.
(forgive my bad english)
can someone know what is happening? I'm using virtualenv with python 2.7

**Comment by RNabel** [comment]
Hey! Are you using the PyPI version (i.e. installed with `pip install PyDrive`) or the newest version from GitHub?

**Comment by xyzrico** [comment]
Oh yes. I used the code from the official documentation `gauth.LocalWebserverAuth()`.
I just tried to change with `gauth.CommandLineAuth()` to see the difference.
I'm using the PyPI version. not  installed with `pip install PyDrive`. I downloaded the archive
and its requirements, and build/install throws setup.py.
I working on windows. I still don't know how to paste the exception stack trace from the console

**Comment by RNabel** [comment]
Ah, I see. Thank you for details! 
If you want to use `CommandLineAuth()` make sure that the code you can see on the website is correctly inserted into the console. You can paste the code into the console using the shortcut Shift+Insert. To copy the stack trace from the console, select the text with the mouse and press Ctrl+Insert (which copies the text to the clipboard).

If [this](http://stackoverflow.com/a/3232999/3918512) StackOverflow answer is correct, then your issue should be solved by the up-to-date version of PyDrive on GitHub. Installation with pip is described [here](https://github.com/googledrive/PyDrive#how-to-install). 
Let me know if this resolves the issue.

**Comment by xyzrico** [comment]
Traceback (most recent call last):
  File "create.py", line 5, in <module>
    gauth.LocalWebserverAuth()
  File "build\bdist.win32\egg\pydrive\auth.py", line 79, in _decorated
  File "build\bdist.win32\egg\pydrive\auth.py", line 394, in Auth
  File "build\bdist.win32\egg\pydrive\auth.py", line 407, in Authenticate
  File "build\bdist.win32\egg\oauth2client\util.py", line 135, in positional_wrapper
  File "build\bdist.win32\egg\oauth2client\client.py", line 2117, in step2_exchange
  File "E:\temp\python google\icardo\lib\site-packages\httplib2-0.9.1-py2.7.egg\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "E:\temp\python google\icardo\lib\site-packages\httplib2-0.9.1-py2.7.egg\httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "E:\temp\python google\icardo\lib\site-packages\httplib2-0.9.1-py2.7.egg\httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "C:\Python27\Lib\httplib.py", line 1123, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

Here is the stack trace.

**Comment by RNabel** [comment]
Interesting. This seems to be an issue with httplib2 (looking at this httplib2 [issue](https://github.com/jcgregorio/httplib2/issues/284) which looks identical to your problem). Could you update httplib2? The newest version is 0.9.2, you can check which version you have by running `pip.exe freeze` (or just `pip freeze` depending on your setup). One line of the output will be `httplib2==0.8.0` or similar.

If the installed version is not the newest version, run `pip.exe install -U httplib2`. The `-U` flag forces the library to be updated. When the httplib2 library is updated, try running your code again.

**Comment by xyzrico** [comment]
I checked. my httplib2 version is 0.9.2. But now I get an socket.error [errno 10013]
Traceback (most recent call last):
  File "create.py", line 5, in <module>
    gauth.LocalWebserverAuth()
  File "build\bdist.win32\egg\pydrive\auth.py", line 79, in _decorated
  File "build\bdist.win32\egg\pydrive\auth.py", line 394, in Auth
  File "build\bdist.win32\egg\pydrive\auth.py", line 407, in Authenticate
  File "build\bdist.win32\egg\oauth2client\util.py", line 135, in positional_wrapper
  File "build\bdist.win32\egg\oauth2client\client.py", line 2117, in step2_exchange
  File "E:\temp\python google\icardo\lib\site-packages\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "E:\temp\python google\icardo\lib\site-packages\httplib2\__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "E:\temp\python google\icardo\lib\site-packages\httplib2\__init__.py", line 1272, in _conn_request
    conn.connect()
  File "E:\temp\python google\icardo\lib\site-packages\httplib2\__init__.py", line 1075, in connect
    raise socket.error, msg
socket.error: [Errno 10013] Une tentative d'accès à un socket de manière interdite par ses autorisations d'accès a été tentée
(translation: An attempt was made to access a socket in a way forbidden by its access permissions)

**Comment by RNabel** [comment]
Cool, good to see that there is some progress. From a quick Google search, I found [this](http://stackoverflow.com/questions/2778840/socket-error-errno-10013-an-attempt-was-made-to-access-a-socket-in-a-way-forb) and [this](http://stackoverflow.com/questions/550032/what-causes-python-socket-error) StackOverflow answer, which indicate that the new issue you are experiencing has to do with Windows permission problems. 
Could you try the solutions suggested in those posts and reply here to indicate whether they solved your problem?

**Comment by RNabel** [comment]
Closing due to inactivity. Feel free to reopen if the problem persists.

**Comment by xyzrico** [comment]
sorry for the late.
It was my firewall.
Now I when I accept the connection with my drive, I do not get
that socket.error: [Errno 10013], but there's nothing going on in my console.
The display remains locked on `https://accounts.google.com/o/oauth2/auth?...`
and I can not even stop all with ctrl + c.
I do not think my connection is so slow.

**Comment by RNabel** [comment]
This appears to be a problem related to your setup. You can try copy-pasting the URL into another browser or in an incognito window, as this error may have to do with the browser you are using.
All information, such as which URL to go to after finishing the oauth process, are encoded in the URL, so it doesn't matter with which browser you open it (as long as it is a browser on the same computer).

If you continue having problems with this issue, please post it on StackOverflow, as it is not directly related to PyDrive.

Good luck :)

**Comment by xyzrico** [comment]
Ok; thank you. I tried with [https://www.pythonanywhere.com](url).
And it worked. so I supposed, it's my computer.
The topic is solved.
Any idea of I can write a stream of data directly in my drive ?
like download a file and redirect destination directly to my drive.

**Comment by RNabel** [comment]
Yep, there are a bunch of options. The simplest is to install the Google Drive Sync client for Windows (which I assume you are using), and then download the file into a folder managed by the sync client. Depending on your understanding of Python you can also write a little program to upload every file you place in a specific folder.

If you are using Linux, have a look at [GDriveFS](https://github.com/dsoprea/GDriveFS) and [google-drive-ocamlfuse](google-drive-ocamlfuse) which both allow you to mount your Google Drive as a local hard drive.

**Comment by xyzrico** [comment]
Good idea. What I want to do is create a free online service that ask the user a downlaod link, and access to his drive, and that service should download the file for him and upload to his drive.
But a free account on PythonAnyWhere is limited to 500mb.  This is a big limitation for my project.
If I could download the file but the stream of data will not be write on the local hard drive. I would be write on the drive.

**Comment by RNabel** [comment]
This is theoretically possible, but not with PyDrive. 
You could use a setup similar to [this](http://stackoverflow.com/a/16696317/3918512) to download the file in chunks. Then you can, in each iteration, upload each chunk to Google Drive using the REST API, chunked upload example [here](https://developers.google.com/drive/v3/web/manage-uploads#chunking) - you need to click 'Expand for more info'. So, it'd look something like this (pseudo-code a la Python):

```python
# Set up, and authenticate the connection to Google Drive.
download_url = '<your download URL>' 
total_size = 1000  # Would need to gain this information from the download url.

# Create file object on Google Drive with correct total size, file name etc. and gain a session URI (needed for the header sent in the for loop below)  
session_uri = '<your session uri>'

current_position = 0  # The byte position in the uploaded file, where the next block will be inserted
r = requests.get(download_url, stream=True)  # From the SO post for chunked download.

for chunk in r.iter_content(chunk_size=1024): 
    if chunk:
        chunk_length = len(chunk)
        # Make resumeable upload request at position `current_position` of length `chunk_length` to Google Drive, 
        #    as illustrated in the documentation. 
        # The header would contain the session URI, 
        # The line `Content-Range: bytes {current_position}-{current_position + chunk_length}/{total_size}`
        #   and: `Content-Length: {chunk_length}` -- see documentation for all required fields.

print("Upload completed.")  
```

The fact that neither PyDrive nor the google-api-client library for python support this functionality makes this a lot more difficult than it looks. If you figure this out, make sure to share it here :)

Side-note: You may still be able to use the google-api-client to authorize and gain a session URI, however, quickstart instructions [here](https://developers.google.com/drive/v3/web/quickstart/python).

**Comment by xyzrico** [comment]
thanks a lot for you help. as soon as I find a solution. I shall inform you.

**Comment by wzbazinga** [comment]
I met nearly the same problem with @xyzrico and I finally got successful authentication by run my script on AWS instead of my own pc. I guess the GFW may be the reason because I am in China.

**Comment by fatmazayed** [comment]
don't use the same object again [https://stackoverflow.com/questions/3231543/python-httplib-responsenotready](url)
