### ISSUE TITLE
ImportError: No module named 'pydrive.auth'; 'pydrive' is not a package

### ISSUE THREAD

**Issue by diman82** [googledrive/PyDrive#70]
I'm trying to run a simple auth process on python 3.6 windows 64 bit with the sample code:

```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()

drive = GoogleDrive(gauth)
```

And I get an import error message right away:

```
c:\Python36\Scripts>..\python.exe pydrive.py
Traceback (most recent call last):
  File "pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "c:\Python36\Scripts\pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named 'pydrive.auth'; 'pydrive' is not a package
```

How can I resolve this?

**Comment by RNabel** [comment]
1) It looks like the library is not installed, run `pip freeze` and ensure that `PyDrive` is in the list. `pip.exe` should be in the same folder as `python.exe`.
2) Make sure that you are using the GitHub version of the library, since the PyPI version is **not** Py3 compatible. Installation instructions can be found [here](https://github.com/googledrive/PyDrive#how-to-install).

**Comment by diman82** [comment]
Seems everything is installed:

```
root@DD-WRT:/opt/share/pydrive/pydrive# pip2.7 freeze
cffi==1.5.2
cryptography==1.3.1
enum34==1.1.2
ffprobe==0.5
google-api-python-client==1.5.1
httplib2==0.9.2
idna==2.1
iotop==0.6
ipaddress==1.0.16
oauth==1.0.1
oauth2client==3.0.0
PIL==1.1.7
ply==3.8
psutil==2.2.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.1
**PyDrive==1.2.1**
pyOpenSSL==16.0.0
python-onedrive==15.10.5
PyYAML==3.11
requests==2.10.0
rope==0.10.3
ropevim==0.6.0
rsa==3.4.2
simplejson==3.6.5
six==1.10.0
uritemplate==0.6
youtube-dl==2016.7.11
root@DD-WRT:/opt/share/pydrive/pydrive# cd /opt/bin/
root@DD-WRT:/opt/bin# python2
python2    python2.7
root@DD-WRT:/opt/bin# python2.7 pydrive.py
Traceback (most recent call last):
  File "pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/opt/bin/pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named auth
root@DD-WRT:/opt/bin# python2 pydrive.py
Traceback (most recent call last):
  File "pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/opt/bin/pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named auth
```

The issue is replicated on another client (windows machine)

**Comment by RNabel** [comment]
Thank you for the update. Looking at the tracebacks, you are getting two different errors for Python 2 and 3 respectively. Depending on your setup, the Py3 error could indicate that the Py3 interpreter doesn't see the library which you installed with pip2.7. Running `pip3 freeze` (or similar) would be useful to eliminate that possibility.

If you have time, could you run `import pydrive` in the interactive python console for both Python 2 and 3, and post the stack traces here?

In the meantime, I will try to get access to a Windows machine to have a look at this error myself. Thank you for your help!

**Comment by diman82** [comment]
pip3.6 freeze:

```
c:\Python36\Scripts>pip3.6.exe freeze
ffprobe==0.5
google-api-python-client==1.5.1
httplib2==0.9.2
oauth2client==2.2.0
onedrivesdk==1.0.7
pyasn1==0.1.9
pyasn1-modules==0.0.8
PyDrive==1.0.1
python-cloudcracker==0.0.4
PyYAML==3.11
requests==2.10.0
rope==0.10.3
rsa==3.4.2
simplejson==3.8.2
six==1.10.0
uritemplate==0.6
youtube-dl==2016.7.24
```

import pydrive in the interactive python shell:

```
c:\Python36>c:\Python36\python.exe
Python 3.6.0a3 (v3.6.0a3:f3edf13dc339, Jul 11 2016, 21:40:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python36\pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named 'pydrive.auth'; 'pydrive' is not a package
>>>
```

Thanks for checking.

**Comment by diman82** [comment]
I can also confirm, that I get the very same error when running on my embedded device (ARM7 Netgear R700 with Entware-ng installed):

```
root@DD-WRT:/opt/bin# python3.5 pydrive.py
Traceback (most recent call last):
  File "pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/opt/bin/pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named 'pydrive.auth'; 'pydrive' is not a package
root@DD-WRT:/opt/bin# python3.5 pydrive.py
Traceback (most recent call last):
  File "pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/opt/bin/pydrive.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
ImportError: No module named 'pydrive.auth'; 'pydrive' is not a package
```

**Comment by RNabel** [comment]
Test for Python **3.5** for version 1.0.1: cannot reproduce error (on Windows Server 2012 64-bit). 
Steps taken: 

- Navigate `Python35\Scripts` with cmd. 
- Run `pip.exe install PyDrive`. 
- Navigate back to `Python35\`. 
- Run `python.exe` and type in `import pydrive`. 

Will try to reproduce with Py27 and version 1.2.1. Note, however, that the version of the library you are using with Py3.5 is 1.0.1, please upgrade to 1.2.1 for Py3 compatibility.

In the setups which say that `'pydrive' is not a package` could you try running `pip show PyDrive` and then in then in the respective interactive interpreter run

```python
import os
try:
    user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
except KeyError:
    user_paths = []
```
Make sure that the location printed with `pip show` is in the path.

If that doesn't work, is there any chance that you are missing the `__init__.py` in the package? Did you edit the contents of the library in any way? If you edited the lib in Win it could have introduced Win-style line endings, which could result in the error you are seeing.

**Comment by diman82** [comment]
OK, these are the findings:

c:\Python36> Scripts\pip3.6.exe show pydrive
---
```
Metadata-Version: 1.0
Name: PyDrive
Version: 1.0.1
Summary: Google Drive API made easy.
Home-page: http://pypi.python.org/pypi/PyDrive/
Author: JunYoung Gwak
Author-email: jgwak@dreamylab.com
License: LICENSE
Location: **c:\python36\lib\site-packages**
Requires: google-api-python-client, PyYAML
Classifiers:
```

```
c:\Python36>python.exe
Python 3.6.0a3 (v3.6.0a3:f3edf13dc339, Jul 11 2016, 21:40:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrive
>>> import os
>>> try:
...     user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
... except KeyError:
...     user_paths = []
...
>>>
>>> user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
>>> print(user_paths)
['c:\\python36\\lib', 'c:\\python36\\DLLs', 'c:\\python36\\lib\\site-packages', '']
```
Reinstalling (by pip) yields the same 1.0.1 version:

```
c:\Python36>Scripts\pip3.6.exe uninstall pydrive
Uninstalling PyDrive-1.0.1:
  c:\python36\lib\site-packages\pydrive-1.0.1-py3.6.egg-info
  c:\python36\lib\site-packages\pydrive\__init__.py
  c:\python36\lib\site-packages\pydrive\apiattr.py
  c:\python36\lib\site-packages\pydrive\auth.py
  c:\python36\lib\site-packages\pydrive\drive.py
  c:\python36\lib\site-packages\pydrive\files.py
  c:\python36\lib\site-packages\pydrive\settings.py
  c:\python36\lib\site-packages\pydrive\test\__init__.py
  c:\python36\lib\site-packages\pydrive\test\test_file.py
  c:\python36\lib\site-packages\pydrive\test\test_filelist.py
  c:\python36\lib\site-packages\pydrive\test\test_oauth.py
Proceed (y/n)? y
  **Successfully uninstalled PyDrive-1.0.1**

c:\Python36>
c:\Python36>
c:\Python36>Scripts\pip3.6.exe install pydrive
Collecting pydrive
  Using cached PyDrive-1.0.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): google-api-python-client>=1.2 in c:\python36\lib\site-packages (from pydrive)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.0 in c:\python36\lib\site-packages (from pydrive)
Requirement already satisfied (use --upgrade to upgrade): uritemplate<1,>=0.6 in c:\python36\lib\site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): six<2,>=1.6.1 in c:\python36\lib\site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): oauth2client in c:\python36\lib\site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): httplib2<1,>=0.8 in c:\python36\lib\site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.5.0 in c:\python36\lib\site-packages (from uritemplate<1,>=0.6->google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in c:\python36\lib\site-packages (from oauth2client->google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in c:\python36\lib\site-packages (from oauth2client->google-api-python-client>=1.2->pydrive)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in c:\python36\lib\site-packages (from oauth2client->google-api-python-client>=1.2->pydrive)
Installing collected packages: pydrive
  Running setup.py install for pydrive ... done
**Successfully installed pydrive-1.0.1**
```

__init__.py is IN the package, but it's blank (size 0).
Win-style line endings ISN'T a problem, as I use the 'EOL conversion => UNIX/OSX format' option.

Finally, I downloaded and updated the package manually (downloading packaged zip master trunk and substituting the pydrive module installed), but the same error remains..

**Comment by diman82** [comment]
Feeling stupid ((
Sorry, I'm not very python proficient )

Thanks for the help, all working is working now.

**Comment by RNabel** [comment]
Glad to hear it! Good luck with your project :)

**Comment by shakesBeardZ** [comment]
changing the name worked for me thankz :)
