### ISSUE TITLE
How to find a file with id ?

### ISSUE THREAD

**Issue by janihur** [googledrive/PyDrive#80]
How to find a file when I only know the `id` ? I'm trying to find the location of a file and thus need to be able to follow the parents.

Example code:

```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()
drive = GoogleDrive(gauth)

query = "title = 'zones.png'"
file_list = drive.ListFile({'q': query}).GetList()

for file in file_list:
  print('-' * 10)
  print(file)

  print('-' * 10)
  # first parent id
  parent_id = file['parents'][0]['id']
  print(parent_id)

  print('-' * 10)
  # How do I get the metadata of the parent ? The search parameters don't support id ?
  # https://developers.google.com/drive/v2/web/search-parameters
  # raises an exception because invalid query
  x = drive.ListFile({'q': "id = '0ByHjqvhF6xI3bWhGWVQ5RVcxTWM'"}).GetList()
  print(x[0])
```

Output:

```
(env) jani@KAKTUS:~/src/google-drive$ python -V
Python 3.4.3
(env) jani@KAKTUS:~/src/google-drive$ pip freeze
google-api-python-client==1.5.5
httplib2==0.9.2
oauth2client==4.0.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
PyDrive==1.3.1
PyYAML==3.12
rsa==3.4.2
six==1.10.0
uritemplate==3.0.0
(env) jani@KAKTUS:~/src/google-drive$ python -m py_compile t2.py && python t2.py
----------
GoogleDriveFile({'fileExtension': 'png', 'headRevisionId': '0B-smeT4cwiP7S0JBWVJWSlB0Y2FWOHdzQ0JENU01UDB3Z2ZJPQ', 'fileSize': '276139', 'version': '1723943', 'editable': True, 'thumbnailLink': 'https://lh5.googleusercontent.com/H2qC4GHgIHy_yB6Fnd0Mm4oA9wxATAzCOckmtcaWMmLqoEFtRDvXBHLMSzsSlsZoerncag=s220', 'writersCanShare': True, 'selfLink': 'https://www.googleapis.com/drive/v2/files/0B-smeT4cwiP7elJ1NGFPTllibVE', 'shared': True, 'id': '0B-smeT4cwiP7elJ1NGFPTllibVE', 'parents': [{'isRoot': False, 'parentLink': 'https://www.googleapis.com/drive/v2/files/0B-smeT4cwiP7TkoxVUpMVWh3X0k', 'id': '0B-smeT4cwiP7TkoxVUpMVWh3X0k', 'kind': 'drive#parentReference', 'selfLink': 'https://www.googleapis.com/drive/v2/files/0B-smeT4cwiP7elJ1NGFPTllibVE/parents/0B-smeT4cwiP7TkoxVUpMVWh3X0k'}], 'labels': {'hidden': False, 'restricted': False, 'starred': False, 'viewed': False, 'trashed': False}, 'spaces': ['drive'], 'userPermission': {'role': 'writer', 'id': 'me', 'type': 'user', 'etag': '"MTSjjTdZYH_6ZlijlPbW5hEYRE4/P-qk5DzxxBe-TH7sS-xPBxr4654"', 'kind': 'drive#permission', 'selfLink': 'https://www.googleapis.com/drive/v2/files/0B-smeT4cwiP7elJ1NGFPTllibVE/permissions/me'}, 'createdDate': '2014-03-31T21:14:31.834Z', 'appDataContents': False, 'lastModifyingUser': {'picture': {'url': 'https://lh3.googleusercontent.com/-DP9WW4xB9OY/AAAAAAAAAAI/AAAAAAAAAUg/nMX8hWYiJ5w/s64/photo.jpg'}, 'emailAddress': 'John.Doe@acme.com', 'displayName': 'John Doe', 'permissionId': '10457895607601373814', 'isAuthenticatedUser': False, 'kind': 'drive#user'}, 'modifiedDate': '2014-03-31T21:14:31.834Z', 'title': 'zones.png', 'etag': '"MTSjjTdZYH_6ZlijlPbW5hEYRE4/MTM5NjMwMDQ3MTgzNA"', 'webContentLink': 'https://docs.google.com/a/acme.com/uc?id=0B-smeT4cwiP7elJ1NGFPTllibVE&export=download', 'originalFilename': 'zones.png', 'quotaBytesUsed': '0', 'markedViewedByMeDate': '1970-01-01T00:00:00.000Z', 'lastModifyingUserName': 'John Doe', 'ownerNames': ['John Doe'], 'downloadUrl': 'https://doc-14-3c-docs.googleusercontent.com/docs/securesc/vf6ehu2p2t1gseilmp2uhub1l2u98p3f/e9dualtiu3ntviua9iglljhl92evvoen/1478433600000/10457895607601373814/17284584118151459308/0B-smeT4cwiP7elJ1NGFPTllibVE?h=04840798280145194859&e=download&gd=true', 'alternateLink': 'https://drive.google.com/a/acme.com/file/d/0B-smeT4cwiP7elJ1NGFPTllibVE/view?usp=drivesdk', 'iconLink': 'https://ssl.gstatic.com/docs/doclist/images/icon_11_image_list.png', 'imageMediaMetadata': {'height': 537, 'width': 680}, 'explicitlyTrashed': False, 'owners': [{'picture': {'url': 'https://lh3.googleusercontent.com/-DP9WW4xB9OY/AAAAAAAAAAI/AAAAAAAAAUg/nMX8hWYiJ5w/s64/photo.jpg'}, 'emailAddress': 'John.Doe@acme.com', 'displayName': 'John Doe', 'permissionId': '10457895607601373814', 'isAuthenticatedUser': False, 'kind': 'drive#user'}], 'mimeType': 'image/png', 'copyable': True, 'kind': 'drive#file', 'md5Checksum': '768dfdd8103214b4f5b265c11f84ce4b'})
----------
0B-smeT4cwiP7TkoxVUpMVWh3X0k
----------
Traceback (most recent call last):
  File "t2.py", line 21, in <module>
    x = drive.ListFile({'q': "id = '0ByHjqvhF6xI3bWhGWVQ5RVcxTWM'"}).GetList()
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/pydrive/apiattr.py", line 162, in GetList
    for x in self:
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/pydrive/apiattr.py", line 146, in __next__
    result = self._GetList()
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/pydrive/files.py", line 64, in _GetList
    http=self.http)
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/mnt/d/src/google-drive/env/lib/python3.4/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v2/files?alt=json&maxResults=1000&q=id+%3D+%270ByHjqvhF6xI3bWhGWVQ5RVcxTWM%27 returned "Invalid query">
(env) jani@KAKTUS:~/src/google-drive$
```

**Comment by RNabel** [comment]
Have a look here: http://stackoverflow.com/a/40327370/3918512. 
Basically use `drive.CreateFile()` with the id and call `FetchMetadata()` on the created object.

**Comment by janihur** [comment]
That was a perfect answer ! Too bad I was not able to find it from the docs ... To me `CreateFile()` sounds a way to create a brand new file - not to create a proxy for a file in Google Drive.

Here is the working example:

```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()
drive = GoogleDrive(gauth)

query = "title = 'zones.png'"
file_list = drive.ListFile({'q': query}).GetList()

for file in file_list:
  print('-' * 10)
  print(file)

  print('-' * 10)
  # first parent id
  parent_id = file['parents'][0]['id']
  print(parent_id)

  print('-' * 10)
  x = drive.CreateFile({'id': parent_id})
  x.FetchMetadata()
  print(x)
```

**Comment by RNabel** [comment]
@janihur I totally agree, this is a bit counter-intuitive. When we get around to refactoring to pep8 + Drive API v3 this is definitely to be changed.
