### ISSUE TITLE
Unable to initiate auth due to failure to import modules

### ISSUE THREAD

**Issue by PcoWegenenVerkeer** [googledrive/PyDrive#87]
Hi,

I installed PyDrive this way on a fresh machine:
`root@xyz:~# pip install PyDrive
Downloading/unpacking PyDrive
  Downloading PyDrive-1.3.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.0 in /usr/lib/python2.7/dist-packages (from PyDrive)
Downloading/unpacking google-api-python-client>=1.2 (from PyDrive)
  Downloading google_api_python_client-1.5.5-py2.py3-none-any.whl (51kB): 51kB downloaded
Downloading/unpacking oauth2client>=4.0.0 (from PyDrive)
  Downloading oauth2client-4.0.0-py2.py3-none-any.whl (184kB): 184kB downloaded
  1 import socket
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.1,<2dev in /usr/local/lib/python2.7/dist-packages (from google-api-python-client>=1.2->PyDrive)
Downloading/unpacking uritemplate>=3.0.0,<4dev (from google-api-python-client>=1.2->PyDrive)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Downloading/unpacking httplib2>=0.9.2,<1dev (from google-api-python-client>=1.2->PyDrive)
  Downloading httplib2-0.9.2.zip (210kB): 210kB downloaded
  Running setup.py (path:/tmp/pip_build_root/httplib2/setup.py) egg_info for package httplib2
    
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->PyDrive)
import socket
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->PyDrive)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->PyDrive)
Installing collected packages: PyDrive, google-api-python-client, oauth2client, uritemplate, httplib2
  Found existing installation: oauth2client 1.3.2
    Uninstalling oauth2client:
      Successfully uninstalled oauth2client
  Found existing installation: httplib2 0.9
    Uninstalling httplib2:
      Successfully uninstalled httplib2
  Running setup.py install for httplib2
    
Successfully installed PyDrive google-api-python-client oauth2client uritemplate httplib2
Cleaning up...`

I try to run small program:
`from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()

drive = GoogleDrive(gauth)

myfile = drive.CreateFile({
    "id": "aaaabbbbccccc"
})
myfile.GetContentFile('dest.csv', mimetype='text/csv')`

I get this error:
`python downcsv.py 
Traceback (most recent call last):
  File "downcsv.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 9, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ImportError: No module named service_account`

I commented out line 9 in "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", then I get this error:
`python downcsv.py 
Traceback (most recent call last):
  File "downcsv.py", line 1, in <module>
    from pydrive.auth import GoogleAuth
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 17, in <module>
    from oauth2client._helpers import scopes_to_string
ImportError: No module named _helpers`

When commenting out line 17 to, I get other errors (what I could expect).

I upgraded PyDrive using pip install git+https://github.com/googledrive/PyDrive.git#egg=PyDrive --upgrade
I upgraded pip install google-api-python-client --upgrade and pip install oauth2client --upgrade but no improvement. 

I guess the issue is somewhat related to https://github.com/googledrive/PyDrive/issues/78 

Thanks for having a look into this!

**Comment by RNabel** [comment]
Hi @PcoWegenenVerkeer, thank you for opening an issue here. oauth2client had a major version upgrade some time ago and as you can see a couple of the compatibility fixes were rather fragile (yep, it's in #78). 
If you find a solution to this problem before I do, feel free to open a PR!

**Comment by RNabel** [comment]
Alright, I just had a look at this again - I was not able to reproduce the problem. Looking at your logs again, it appears to be related to the following:
```
Installing collected packages: PyDrive, google-api-python-client, oauth2client, uritemplate, httplib2
Found existing installation: oauth2client 1.3.2
Uninstalling oauth2client: <--------- 
Successfully uninstalled oauth2client
```

Could you run `pip freeze` and check which version of `oauth2client` was installed?

**Comment by RNabel** [comment]
Closing this issue due to inactivity and irreproducibility.
