### ISSUE TITLE
Logging in with OAuth2Credentials object

### ISSUE THREAD

**Issue by MarcoBuster** [googledrive/PyDrive#89]
Hello,
I'm using a `oauth2client` Google module:
```python
from oauth2client.client import OAuth2WebServerFlow


flow = OAuth2WebServerFlow(client_id='client id',
                           client_secret='secret',
                           scope='https://www.googleapis.com/auth/drive',
                           redirect_uri='https://callback.marcoaceti.it/drive_callback')
auth_uri = flow.step1_get_authorize_url()
print('Click this link: ' + auth_uri)

credentials = flow.step2_exchange(input('Insert code: '))
```
And all works. But, if I try to use pydrive module _from_ `OAuth2Credentials` object (saved in `credentials`), I get an error:
```python
from pydrive.drive import GoogleDrive
drive = GoogleDrive(guath)

for file_list in drive.ListFile({'q': "'{dir}' in parents and trashed=false".format(dir="root")}):
    files = ''
    for file1 in file_list:
        files += 'title: %s, id: %s' % (file1['title'], file1['id'])

print(files)
```
```python
Traceback (most recent call last):
  File "/Users/casa/Desktop/Progetti/Bot/GoogleBot/callback.py", line 19, in <module>
    for file_list in drive.ListFile({'q': "'{dir}' in parents and trashed=false".format(dir=dir)}):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pydrive/apiattr.py", line 146, in __next__
    result = self._GetList()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pydrive/auth.py", line 60, in _decorated
    if self.auth.service is None:
AttributeError: 'OAuth2Credentials' object has no attribute 'service'
```
How can I fix it? I can't use the `pydrive.auth` module, because this credentials should be valid for all related Google services.

**Comment by RNabel** [comment]
I'm afraid you can't use the `OAuth2Credentials` object directly, as `gauth` is of type `GoogleAuth`. 

That being said, nothing stops you from wiring your OAuth2Credentials directly into the `GoogleAuth` instance.

You can try the following: (not tested)

```python
credentials = # The OAuth2Credentials object
gauth = GoogleAuth()
gauth.credentials = credentials # Set your credentials object directly rather than going through PyDrive flow.
gauth.Authorize() # Builds the `service` object.
# Note: gauth.Authorize() is not needed here, as it will be called if the `service` object is `None`. 
#    Calling it directly will flag any errors with this authentication method early.

# PyDrive usage as normal...
```

Let me know if this makes your code work!
