### ISSUE TITLE
Is there something I'm missing when setting client_user_email for service_config

### ISSUE THREAD

**Issue by richiverse** [googledrive/PyDrive#91]
I had a working implementation up until I wanted to remove folder sharing to the service account and allow it to assume the role of the user that created the service account. I figured setting client_user_email would achieve this.

https://github.com/googledrive/PyDrive/blob/master/pydrive/auth.py#L274-L275

Context:
I'm unable to share a service account email directly with a folder as it is external to our domain and we disallow external sharing. In addition, I'm using aws lambda https://github.com/richiverse/gdrive-lambda as a wrapper to pydrive to serve it from API Gateway so it needs to go through the service account. Is there some setting I'm missing from the google console (https://console.developers.google.com)

In addition, I'm not able to give domain wide access to all users data from this service account so I just need a proxy user for the service account to access files that the proxy user has access to.

Is this achievable with pydrive?

`settings.yaml`
```
client_config_backend: service
service_config:
  client_service_email: lambda-pydrive@xxxxxxxxxxxxxxx.iam.gserviceaccount.com
  client_user_email: richard.fernandez.nyc@gmail.com
  client_pkcs12_file_path: client_secrets-dev.p12
```

```[1489004018916] [WARNING] 2017-03-08T20:13:38.916Z b42cb626-043b-11e7-9abd-e75685be99b6 file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/tmp/pip-build-BEA64O/google-api-python-client/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
  File "/tmp/pip-build-BEA64O/google-api-python-client/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
[1489004018917] [INFO] 2017-03-08T20:13:38.916Z b42cb626-043b-11e7-9abd-e75685be99b6 URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
[1489004018917] [INFO] 2017-03-08T20:13:38.917Z b42cb626-043b-11e7-9abd-e75685be99b6 Attempting refresh to obtain initial access_token
[1489004018919] [DEBUG] 2017-03-08T20:13:38.918Z b42cb626-043b-11e7-9abd-e75685be99b6 ['xxxxxxxx', 'xxx$xxx', 'xxxxx']
[1489004018919] [INFO] 2017-03-08T20:13:38.919Z b42cb626-043b-11e7-9abd-e75685be99b6 Refreshing access_token
[1489004019113] [INFO] 2017-03-08T20:13:39.113Z b42cb626-043b-11e7-9abd-e75685be99b6 Failed to retrieve access token: {
 "error": "unauthorized_client",
 "error_description": "Client is unauthorized to retrieve access tokens using this method."
}
[1489004019114] unauthorized_client: Client is unauthorized to retrieve access tokens using this method.: HttpAccessTokenRefreshError
Traceback (most recent call last):
  File "/var/task/handler.py", line 520, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 230, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 124, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
  File "/var/task/app.py", line 24, in <module>
  gauth.ServiceAuth()
  File "/home/rich/Projects/github/gdrive-lambda/venv/lib/python2.7/site-packages/pydrive/auth.py", line 89, in _decorated
  File "/home/rich/Projects/github/gdrive-lambda/venv/lib/python2.7/site-packages/pydrive/auth.py", line 523, in Authorize
  File "/tmp/pip-build-BEA64O/oauth2client/oauth2client/_helpers.py", line 133, in positional_wrapper
  File "/tmp/pip-build-BEA64O/google-api-python-client/googleapiclient/discovery.py", line 222, in build
  File "/tmp/pip-build-BEA64O/google-api-python-client/googleapiclient/discovery.py", line 269, in _retrieve_discovery_doc
  File "/tmp/pip-build-BEA64O/oauth2client/oauth2client/transport.py", line 159, in new_request
  File "/tmp/pip-build-BEA64O/oauth2client/oauth2client/client.py", line 744, in _refresh
  File "/tmp/pip-build-BEA64O/oauth2client/oauth2client/client.py", line 812, in _do_refresh_request
```

```
HttpAccessTokenRefreshError: unauthorized_client: Client is unauthorized to retrieve access tokens using this method.
```

**Comment by richiverse** [comment]
pls close for now. I had to enable domain wide delegation for this to work
